### ISSUE TITLE
Where does this show up?

### ISSUE THREAD

**Issue by Ph0rk0z** [theroyallab/ST-tabbyAPI-loader#2]
Should it be under extensions? On the connection page? I don't get any kind of box to load a model but I do get the list of my models in the console of ST.

**Comment by heffke** [comment]
It's supposed to show up in the Extensions menu, but unfortunately SillyTavern has [made a breaking change](https://github.com/SillyTavern/SillyTavern/commit/047c897ead7c9c04fe473844cd71f16707c3a705).
Replacing instances of `isTabby()` to `textgen_settings.type === textgen_types.TABBY` (with the appropriate imports) fixes that, but there is still another issue in the extension itself with loading its settings, bandaid fix is commenting out `await loadSettings();` in `index.js`. It will then work, but obviously not keep your settings through sessions.

**Comment by kingbri1** [comment]
Thanks for letting me know! I've fixed that with b2cb63af7e9ade2e34eb5697aee61e65f4d22a9f.

As for finding the extension menu. @heffke summarized it perfectly. The options are located in the Extensions menu > TabbyAPI loader. Again, the extension is currently a WIP and can load models with default settings (no extra rope parameters/draft models just yet).

**Comment by Ph0rk0z** [comment]
That explains it. I will pull changes and test. I don't really use too much rope settings so having *any* switching ability is a plus.

**Comment by Ph0rk0z** [comment]
Unfortunately after updating ST stagin, tabby api and the extension it's still not showing up in the extensions list.

**Comment by Ph0rk0z** [comment]
It works now. Was able to load/unload.
